podTemplate(containers: [
    containerTemplate(name: 'jnlp', image: 'harbor.dev.rdev.tech/library/jenkins/sonar_maven:v1.0.8_alpha', ttyEnabled: true)
  ],
    volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
                hostPathVolume(hostPath: '/usr/local/bin/docker', mountPath: '/usr/local/bin/docker'),
                hostPathVolume(hostPath: '/usr/local/bin/kubectl', mountPath: '/usr/local/bin/kubectl')]) {
node(POD_LABEL) {
    stage('Get a Maven project') {
            git  credentialsId: 'lmg_ssh_1', url: 'ssh://git@gitlab.dev.rdev.tech:10022/lmgtest/zhjk.git', branch: 'dev-20201020'
        }
    stage('Build Project'){
            sh "sed -i s#http://192.168.81.103:8081#https://nexus-dev.rdev.tech#g /usr/share/maven/conf/settings.xml"
            sh "sed -i s/abc123B,/Def@u1tpwd/g /usr/share/maven/conf/settings.xml"
            sh "mvn -f pom.xml clean package -Dmaven.wagon.http.ssl.insecure=true"
        }
    stage('Sonar Scanner'){
            sh "sonar-scanner -X "+
            "-Dsonar.host.url=http://192.168.80.80:30002 " +
            "-Dsonar.login=7eeea6720241874895a09ef394b5d8ef4e0af7dc " +
            "-Dsonar.language=java " + 
            "-Dsonar.projectKey=zjk-cms-inner " + 
            "-Dsonar.projectName=zjk-cms-inner " + 
            "-Dsonar.projectVersion=$BUILD_NUMBER " + 
            "-Dsonar.sources=rmemis-inner/ " + 
            "-Dsonar.sourceEncoding=UTF-8 " + 
            "-Dsonar.java.binaries=."
        }
    stage('Build Docker image'){
            sh  """
            mkdir -p bak/inner
            cp rmemis-inner/target/rmei.war bak/inner/
            cd bak/inner
            cp ../../CI/configuration/inner/Dockerfile .
            cp ../../CI/configuration/inner/wExperts.ini .
            docker login -u admin -pDef@u1tpwd harbor.dev.rdev.tech
            docker build -t harbor.dev.rdev.tech/gt_zjk/inner:$BUILD_NUMBER .
            docker push harbor.dev.rdev.tech/gt_zjk/inner:$BUILD_NUMBER
            docker rmi harbor.dev.rdev.tech/gt_zjk/inner:$BUILD_NUMBER
            """
        }
    stage('Deploy'){
            sh """
            git reset --hard
            cd CI/configuration/inner/yaml
            cat rmemis-inner.yaml
            sed -i s/inner:[[:digit:]]*\$/inner:$BUILD_NUMBER/g rmemis-inner.yaml
            cat rmemis-inner.yaml
            cd ../../../../
            git config --global user.name liminggang
            git config --global user.email mensyli@dingtalk.com
            git remote set-url origin ssh://git@gitlab.dev.rdev.tech:10022/lmgtest/zhjk.git
            git clean -df
            cp -f /root/config .git/config
            git add CI/configuration/inner/yaml/rmemis-inner.yaml
            git commit -m 'update tag by jenkins'
            git push --set-upstream origin dev-20201020
            """                
        }
    stage('Test'){
         meterSphere msEndpoint:'http://192.168.80.89:8081/',
         msAccessKey:'kRMWd2OcaV2namaI',
         msSecretKey:'sOvlpQLpaPkZt7gD',
         workspaceId: '3198dac7-ab6a-490d-a2e3-2888f21a8565',
         projectId: 'e75b0c89-0637-40f3-b794-6e6ba097c42c',
         method:'testPlan',
         testPlanId: 'c9282348-4842-41c2-a99b-26d600233eef', 
         testCaseId: '', 
         result: 'jenkins'
        }
    }
} 

