---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opendjpvc
  labels:
    app: opendj
    chart: "opendj3.0"
    release: "rf"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"
  storageClassName: "nfs-client"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendj
  labels:
    app: opendj
    chart: "opendj3.0"
    release: "rf"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: opendj
      chart: "opendj3.0"
      release: "rf"
      heritage: "Tiller"
  template:
    metadata:
      labels:
        app: opendj
        chart: "opendj3.0"
        release: "rf"
        heritage: "Tiller"
    spec:
      containers:
      - name: opendj
        image: 192.168.106.196:8081/opendj/opendj:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_PASSWORD
          value: opendj
        ports:
        - name: port1
          containerPort: 1389
        - name: port2
          containerPort: 4444         
        volumeMounts:
        - name: opendj-db
          mountPath: /apps/opendj/db
          subPath: 
      volumes:
      - name: opendj-db
        persistentVolumeClaim:
          claimName: opendjpvc
          
---

apiVersion: v1
kind: Service
metadata:
  name: opendj-svc
  labels:
    app: opendj
    chart: "opendj3.0"
    release: "rf"
    heritage: "Tiller"
  annotations:    
spec:
  type: NodePort
  ports:
  - name: port1
    port: 1389
    targetPort: port1
  - name: port2
    port: 4444
    targetPort: port2
  selector:
    app: opendj
