---
- name: Configure defaults
  debug:
    msg: "Check roles/kubespray-defaults/defaults/main.yml"
  tags:
    - always

- name: "Set up proxy environment"
  set_fact:
    proxy_env:
      http_proxy: "{{ http_proxy | default ('http://192.168.80.11:8443') }}"
      HTTP_PROXY: "{{ http_proxy | default ('http://192.168.80.11:8443') }}"
      https_proxy: "{{ https_proxy | default ('https://192.168.80.11:8443') }}"
      HTTPS_PROXY: "{{ https_proxy | default ('https://192.168.80.11:8443') }}"
      no_proxy: "{{ no_proxy | default ('') }}"
      NO_PROXY: "{{ no_proxy | default ('') }}"
  no_log: true
  tags:
    - always

# do not run gather facts when bootstrap-os in roles
- name: set fallback_ips
  import_tasks: fallback_ips.yml
  when:
    - "'bootstrap-os' not in ansible_play_role_names"
    - fallback_ips is not defined
  tags:
    - always

- name: set no_proxy
  import_tasks: no_proxy.yml
  when:
    - "'bootstrap-os' not in ansible_play_role_names"
    - http_proxy is defined or https_proxy is defined
    - no_proxy is not defined
  tags:
    - always
