kind: Secret
apiVersion: v1
metadata:
  name: gitlab-postgresql
  namespace: gitlab-dev
  labels:
    app: gitlab-postgresql
    chart: postgresql-0.8.1
    heritage: Tiller
    release: gitlab
data:
  postgres-password: Z2l0bGFi
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: gitlab-redis
  namespace: gitlab-dev
  labels:
    app: gitlab-redis
    chart: redis-0.9.0
    heritage: Tiller
    release: gitlab
data:
  redis-password: SzBVeHBDbWhEOA==
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: gitlab-gitlab-ce
  namespace: gitlab-dev
  labels:
    app: gitlab-gitlab-ce
    chart: gitlab-ce-0.2.2
    heritage: Tiller
    release: gitlab
data:
  db-password: Z2l0bGFi
  db-user: Z2l0bGFi
  gitlab-root-password: MXFhekBXU1g=
type: Opaque































