kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    app: argocd
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "nfs-client-3"