apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "14"
      kubesphere.io/alias-name: gitlab
      kubesphere.io/maxSurgePod: "2"
      kubesphere.io/minAvailablePod: "1"
    creationTimestamp: "2020-12-25T05:37:51Z"
    generation: 25
    labels:
      app: gitlab
    name: gitlab-3as1am
    namespace: gitlab3
    resourceVersion: "147323017"
    selfLink: /apis/extensions/v1beta1/namespaces/gitlab2/deployments/gitlab-3as1am
    uid: f0624e9d-f6cd-4633-9063-cf94f9f0acd8
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: gitlab
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubesphere.io/containerSecrets: '{"container-25yoy0":"harbor"}'
          kubesphere.io/restartedAt: "2020-12-25T07:12:23.635Z"
          logging.kubesphere.io/logsidecar-config: '{}'
        creationTimestamp: null
        labels:
          app: gitlab
      spec:
        affinity: {}
        containers:
        - env:
          - name: GITLAB_OMNIBUS_CONFIG
            valueFrom:
              configMapKeyRef:
                key: gitlab_omnibus_config
                name: gitlab-cm
          image: reg.k8s.rf.io/gitlab/gitlab-ce:13.6.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /help
              port: tcp-80
              scheme: HTTP
            initialDelaySeconds: 200
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: container-25yoy0
          ports:
          - containerPort: 22
            name: tcp-22
            protocol: TCP
          - containerPort: 443
            name: tcp-443
            protocol: TCP
          - containerPort: 80
            name: tcp-80
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /help
              port: tcp-80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/gitlab/ssl
            name: volume-53xm1y
          - mountPath: /var/opt/gitlab
            name: volume-65qfe7
          - mountPath: /var/log/gitlab
            name: volume-qoopca
          - mountPath: /etc/gitlab
            name: volume-k9edx0
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: harbor
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-53xm1y
          secret:
            defaultMode: 420
            secretName: gitlab-pem
        - name: volume-65qfe7
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: volume-qoopca
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: volume-k9edx0
          persistentVolumeClaim:
            claimName: gitlab-config
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-12-25T05:37:51Z"
      lastUpdateTime: "2020-12-25T07:29:07Z"
      message: ReplicaSet "gitlab-3as1am-5776f8b7d4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-12-25T07:31:24Z"
      lastUpdateTime: "2020-12-25T07:31:24Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    observedGeneration: 25
    readyReplicas: 1
    replicas: 2
    unavailableReplicas: 1
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
