kind: Secret
apiVersion: v1
metadata:
  name: gitlab-postgresql
  namespace: gitlab-dev2
  labels:
    app: gitlab-postgresql
data:
  postgres-password: Z2l0bGFi
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: gitlab-redis
  namespace: gitlab-dev2
  labels:
    app: gitlab-redis
data:
  redis-password: SzBVeHBDbWhEOA==
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: gitlab-gitlab-ce
  namespace: gitlab-dev2
  labels:
    app: gitlab-gitlab-ce
data:
  db-password: Z2l0bGFi
  db-user: Z2l0bGFi
  gitlab-root-password: MXFhekBXU1g=
type: Opaque































