replicas: 1

deploymentStrategy: RollingUpdate

image:
  repository: 192.168.80.54:8081/library/crossplane/crossplane:v1.0.0
  tag: v1.0.0
  pullPolicy: Always

leaderElection: true
args: {}

provider:
  packages: []

imagePullSecrets:
- dockerhub

rbacManager:
  deploy: true
  replicas: 1
  managementPolicy: All
  leaderElection: true
  args: {}

priorityClassName: ""

resourcesCrossplane:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContextCrossplane:
  runAsUser: 2000
  runAsGroup: 2000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

packageCache:
  medium: ""
  sizeLimit: 5Mi
  pvc: ""

resourcesRBACManager:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContextRBACManager:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

alpha:
  oam:
    enabled: false

metrics:
  enabled: false
