kind: ConfigMap
apiVersion: v1
metadata:
  name: gitlab-gitlab-ce
  namespace: gitlab-dev
  labels:
    app: gitlab-gitlab-ce
    chart: gitlab-ce-0.2.2
    heritage: Tiller
    release: gitlab
data:
  gitlab_omnibus_config: >
    external_url ENV['EXTERNAL_URL'];

    root_pass = ENV['GITLAB_ROOT_PASSWORD'];

    gitlab_rails['initial_root_password'] = root_pass unless root_pass.to_s ==
    '';

    postgresql['enable'] = false;

    gitlab_rails['db_host'] = ENV['DB_HOST'];

    gitlab_rails['db_password'] = ENV['DB_PASSWORD'];

    gitlab_rails['db_username'] = ENV['DB_USER'];

    gitlab_rails['db_database'] = ENV['DB_DATABASE'];

    gitlab_rails['redis_host'] = ENV['REDIS_HOST'];

    gitlab_rails['redis_password'] = ENV['REDIS_PASSWORD'];

    unicorn['worker_processes'] = 2;

    manage_accounts['enable'] = true;

    manage_storage_directories['manage_etc'] = false;

    gitlab_shell['auth_file'] = '/gitlab-data/ssh/authorized_keys';

    git_data_dir '/gitlab-data/git-data';

    redis['enable'] = false; 

    gitlab_rails['shared_path'] = '/gitlab-data/shared';

    gitlab_rails['uploads_directory'] = '/gitlab-data/uploads';

    gitlab_ci['builds_directory'] = '/gitlab-data/builds';

    gitlab_rails['omniauth_enabled'] = true;

    gitlab_rails['omniauth_allow_single_sign_on'] = ['saml'];

    gitlab_rails['omniauth_block_auto_created_users'] = false;

    gitlab_rails['omniauth_auto_link_saml_user'] = true;

    nginx['redirect_http_to_https'] = true;

    nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab-server.pem";

    nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab-server-key.pem";

    gitlab_rails['gitlab_shell_ssh_port'] = 31146;
    gitlab_rails['omniauth_providers'] = [
      {
        name: 'saml',
        groups_attribute: 'Groups',
        required_groups: ['Admin'],
        args: {
                 assertion_consumer_service_url: 'http://gitlab.rdev.tech/users/auth/saml/callback',
                 idp_cert_fingerprint: '68:87:CF:A6:DF:9D:EB:06:77:50:87:7E:9E:5D:E3:09:C0:F0:70:7C',
                 idp_sso_target_url: 'http://gitlab.rdev.tech/auth/realms/demo/protocol/saml/clients/gitlab.rdev.tech',
                 issuer: 'gitlab.k8s-rf.io',
                 attribute_statements: {
                   first_name: ['first_name'],
                   last_name: ['last_name'],
                   name: ['name'],
                   username: ['name'],
                   email: ['email'] },
                 name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'
               },
        label: 'Company Login' # optional label for SAML login button, defaults to "Saml"
      }
    ];

