apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-gitlab
  namespace: gitlab-dev
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - gitlab.rdev.tech
    secretName: gitlab-ingress-secret
  rules:
  - host: gitlab.rdev.tech
    http:
      paths:
      - path:
        backend:
          serviceName: gitlab
          servicePort: 80