---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: mysql
    chart: mysql-5.0.6
    release: "mysql"
    heritage: "Tiller"
type: Opaque
data:
  mysql-root-password: "MXFhekBXU1g="
  mysql-replication-password: "MXFhekBXU1g="