kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
 namespace: finance-fssc
 name: deployment-manager
rules:
- apiGroups: ["","extensions","apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
 name: deployment-manager-binding
 namespace: finance-fssc
subjects:
- kind: User
  name: chenpeitao
  apiGroup: ""
roleRef:
 kind: ClusterRole
 name: admin
 apiGroup: ""